[build]
builder = "nixpacks"
buildCommand = "cd standalone-chat && pip install -r requirements.txt"

[deploy]
startCommand = "cd standalone-chat && uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
